In [189]:
import random
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [190]:
obj = Series([4, 7, -5, 3])
print(obj)
print(obj.index)
print(obj.values)


0    4
1    7
2   -5
3    3
dtype: int64
RangeIndex(start=0, stop=4, step=1)
[ 4  7 -5  3]


In [191]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
print(obj2)


d    4
b    7
a   -5
c    3
dtype: int64


In [192]:
sdata = {'Texas': 10, 'Ohio': 20, 'Oregon': 15, 'Utah': 18}
states = ['Texas', 'Ohio', 'Oregon', 'Iowa']
obj4 = Series(sdata, index=states)
print(obj4)


Texas     10.0
Ohio      20.0
Oregon    15.0
Iowa       NaN
dtype: float64


## Series Activity

In [193]:


# Create a random list of 10 integers in the range from 1 to 100 
random_list = [random.randint(1, 100) for _ in range(10)]
print(random_list)

# Generate a Series using above list with index values of 1-10
# Name your Series “Random Numbers”
# Name your index “idx”

random_series = pd.Series(random_list, index=range(1, 11), name="Random Numbers")
random_series.index.name = "idx"
print(random_series)

# Now generate the Squares of all the values in the Series
# display last 4 items of this Series
# Also display all the numbers >500 as a list 

squared_series = random_series ** 2
print(squared_series.tail(4))
print(squared_series[squared_series > 500].tolist())


[92, 21, 4, 49, 41, 42, 11, 13, 29, 91]
idx
1     92
2     21
3      4
4     49
5     41
6     42
7     11
8     13
9     29
10    91
Name: Random Numbers, dtype: int64
idx
7      121
8      169
9      841
10    8281
Name: Random Numbers, dtype: int64
[8464, 2401, 1681, 1764, 841, 8281]


### Dataframe

In [194]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
statepop = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['A', 'B', 'C', 'D', 'E'])
print(statepop)


   year   state  pop debt
A  2000    Ohio  1.5  NaN
B  2001    Ohio  1.7  NaN
C  2002    Ohio  3.6  NaN
D  2001  Nevada  2.4  NaN
E  2002  Nevada  2.9  NaN


In [195]:
# transpose the DataFrame
print(statepop.T)


          A     B     C       D       E
year   2000  2001  2002    2001    2002
state  Ohio  Ohio  Ohio  Nevada  Nevada
pop     1.5   1.7   3.6     2.4     2.9
debt    NaN   NaN   NaN     NaN     NaN


Getting specific rows


In [196]:
print(statepop.loc['A'])

print(statepop.loc['A':'E',['state','pop']])

print(statepop.iloc[1:3]) 




year     2000
state    Ohio
pop       1.5
debt      NaN
Name: A, dtype: object
    state  pop
A    Ohio  1.5
B    Ohio  1.7
C    Ohio  3.6
D  Nevada  2.4
E  Nevada  2.9
   year state  pop debt
B  2001  Ohio  1.7  NaN
C  2002  Ohio  3.6  NaN


Modifying columns


In [197]:
# modify statepop to add a new column that doubles the pop column and turns it into an integer
statepop['double_pop'] = (statepop['pop'] * 2).astype(int)
print(statepop)


   year   state  pop debt  double_pop
A  2000    Ohio  1.5  NaN           3
B  2001    Ohio  1.7  NaN           3
C  2002    Ohio  3.6  NaN           7
D  2001  Nevada  2.4  NaN           4
E  2002  Nevada  2.9  NaN           5


In [198]:
# set debt column to zero   
statepop['debt'] = 0
print(statepop)


   year   state  pop  debt  double_pop
A  2000    Ohio  1.5     0           3
B  2001    Ohio  1.7     0           3
C  2002    Ohio  3.6     0           7
D  2001  Nevada  2.4     0           4
E  2002  Nevada  2.9     0           5


In [199]:
#drop the debt column
statepop = statepop.drop('debt', axis=1)
print(statepop)


   year   state  pop  double_pop
A  2000    Ohio  1.5           3
B  2001    Ohio  1.7           3
C  2002    Ohio  3.6           7
D  2001  Nevada  2.4           4
E  2002  Nevada  2.9           5


## Dataframe activity

In [200]:
# Create a numpy array of the shape (3,5): 3 rows and 5 columns  with random values from 1 to 100 
# Use np.random.randint(low,high, (shape)) 
array = np.random.randint(1, 101, (3, 5))
print(array)

[[17 37 25 76 87]
 [86 85 27 57 31]
 [ 6 91 40 98 12]]


In [201]:
# Use the numpy array to generate a Data Frame with index = a,b,c and columns "one" "two" "three" "four" "five"
activitydf = pd.DataFrame(array, index=['a', 'b', 'c'], columns=["one", "two", "three", "four", "five"])
print(activitydf)

   one  two  three  four  five
a   17   37     25    76    87
b   86   85     27    57    31
c    6   91     40    98    12


In [202]:
# Transpose (using .T) the DataFrame and change the values less than 40 to 0 in the Data Frame. 
df_transposed = activitydf.T
df_transposed[df_transposed < 40] = 0
print(df_transposed)


        a   b   c
one     0  86   0
two     0  85  91
three   0   0  40
four   76  57  98
five   87   0   0


In [203]:
# Apply a lambda function to calculate the square root of each value in the data frame
df_sqrt = activitydf.applymap(lambda x: np.sqrt(x))
print(df_sqrt)


        one       two     three      four      five
a  0.000000  0.000000  0.000000  8.717798  9.327379
b  9.273618  9.219544  0.000000  7.549834  0.000000
c  0.000000  9.539392  6.324555  9.899495  0.000000


/var/folders/s4/35mz08191h37fr7zq4g0m_d40000gn/T/ipykernel_9929/3246502174.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_sqrt = activitydf.applymap(lambda x: np.sqrt(x))


## REMEMBER CHECK THE OUTPUT
-- What is wrong?!?!?!?

In [204]:
# our modification went all the way to the original array!!!!

print(array)

[[ 0  0  0 76 87]
 [86 85  0 57  0]
 [ 0 91 40 98  0]]


## LESSON
Be careful when modifying "copied" data that may still be pointing back at the original. 

THIS IS THE LINE:  df_transposed = activitydf.T

This made a new dataframe that was poining to the transposed original. Modifying it, modifies the original.

### The lesson: Always always always verify the output and ask if it makes sense

In [205]:
array2 = np.random.randint(1, 101, (3, 5))
print(array2)
activitydf2 = pd.DataFrame(array2, index=['a', 'b', 'c'], columns=["one", "two", "three", "four", "five"])
print(activitydf2)

# THIS MAKES AN ACTUAL SEPARATE COPY
activitydf2_copy = activitydf2.copy()

activitydf2_transposed = activitydf2_copy.T
activitydf2_transposed[activitydf2_transposed < 40] = 0
print(activitydf2_transposed)

# now try our same operation on the original dataframe
df_sqrt2 = activitydf2.applymap(lambda x: np.sqrt(x))
print(df_sqrt2)

print(array2)


[[53 71 10 45 17]
 [26 85 92 62 46]
 [64  2 54 65 51]]
   one  two  three  four  five
a   53   71     10    45    17
b   26   85     92    62    46
c   64    2     54    65    51
        a   b   c
one    53   0  64
two    71  85   0
three   0  92  54
four   45  62  65
five    0  46  51
       one       two     three      four      five
a  7.28011  8.426150  3.162278  6.708204  4.123106
b  5.09902  9.219544  9.591663  7.874008  6.782330
c  8.00000  1.414214  7.348469  8.062258  7.141428
[[53 71 10 45 17]
 [26 85 92 62 46]
 [64  2 54 65 51]]


/var/folders/s4/35mz08191h37fr7zq4g0m_d40000gn/T/ipykernel_9929/2666985282.py:14: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_sqrt2 = activitydf2.applymap(lambda x: np.sqrt(x))


## Handling Missing Data in Weather Sensor Data

Let's create a synthetic weather dataset that mimics real sensor data with missing values, then explore different methods to handle the missing data.

In [206]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

# Set random seed for reproducibility
np.random.seed(42)

# Create synthetic weather sensor data
n_days = 100
start_date = datetime(2024, 1, 1)
dates = [start_date + timedelta(days=i) for i in range(n_days)]

# Generate base weather data
temperature = np.random.normal(15, 10, n_days)  # Temperature in Celsius
humidity = np.random.normal(60, 20, n_days)     # Humidity percentage
pressure = np.random.normal(1013, 15, n_days)   # Atmospheric pressure in hPa
wind_speed = np.random.exponential(5, n_days)   # Wind speed in km/h
weather_conditions = np.random.choice(['Sunny', 'Cloudy', 'Rainy', 'Foggy'], n_days, 
                                    p=[0.4, 0.3, 0.2, 0.1])

# Create DataFrame
weather_data = pd.DataFrame({
    'date': dates,
    'temperature': temperature,
    'humidity': humidity,
    'pressure': pressure,
    'wind_speed': wind_speed,
    'condition': weather_conditions
})

# Introduce missing values to simulate sensor failures
# More aggressive missing data patterns

# Random missing values (sensor malfunction) - increased frequency
missing_temp = np.random.choice(n_days, size=int(n_days * 0.18), replace=False)
weather_data.loc[missing_temp, 'temperature'] = np.nan

missing_humidity = np.random.choice(n_days, size=int(n_days * 0.15), replace=False)
weather_data.loc[missing_humidity, 'humidity'] = np.nan

missing_pressure = np.random.choice(n_days, size=int(n_days * 0.12), replace=False)
weather_data.loc[missing_pressure, 'pressure'] = np.nan

missing_wind = np.random.choice(n_days, size=int(n_days * 0.20), replace=False)
weather_data.loc[missing_wind, 'wind_speed'] = np.nan

# Sequential missing values (sensor offline for periods)
weather_data.loc[15:22, 'humidity'] = np.nan     # 8-day humidity sensor failure
weather_data.loc[35:41, 'pressure'] = np.nan     # 7-day pressure sensor failure  
weather_data.loc[60:67, 'temperature'] = np.nan  # 8-day temperature sensor failure
weather_data.loc[80:84, 'wind_speed'] = np.nan   # 5-day wind sensor failure

# Multiple sensor failures (power outage scenarios)
weather_data.loc[25:28, ['temperature', 'pressure']] = np.nan
weather_data.loc[55:57, ['humidity', 'wind_speed']] = np.nan
weather_data.loc[72:74, ['temperature', 'humidity', 'pressure']] = np.nan

# Burst failures (intermittent connectivity issues)
burst_days1 = [10, 12, 14, 16]  # Every other day failure pattern
burst_days2 = [45, 47, 49, 51, 53]  # Another burst pattern
weather_data.loc[burst_days1, 'wind_speed'] = np.nan
weather_data.loc[burst_days2, 'humidity'] = np.nan

# Missing categorical data - increased
missing_condition = np.random.choice(n_days, size=int(n_days * 0.12), replace=False)
weather_data.loc[missing_condition, 'condition'] = None

# Additional weekend maintenance patterns (systematic missing data)
weekend_maintenance = [6, 7, 13, 14, 20, 21, 27, 28, 34, 35]  # Simulate weekend maintenance
weather_data.loc[weekend_maintenance, 'pressure'] = np.nan

print("Original Dataset with Missing Values:")
print(weather_data.head(15))
print(f"\nDataset shape: {weather_data.shape}")
print(f"\nMissing values per column:")
print(weather_data.isnull().sum())
print(f"\nPercentage of missing values:")
print((weather_data.isnull().sum() / len(weather_data) * 100).round(2))

Original Dataset with Missing Values:
         date  temperature    humidity     pressure  wind_speed condition
0  2024-01-01    19.967142   31.692585          NaN    1.656669     Sunny
1  2024-01-02    13.617357   51.587094  1021.411768    0.976666     Sunny
2  2024-01-03    21.476885   53.145710          NaN         NaN     Foggy
3  2024-01-04    30.230299   43.954455  1028.807031         NaN     Rainy
4  2024-01-05    12.658466   56.774286   992.334959   23.285024    Cloudy
5  2024-01-06          NaN   68.081017   998.932624    2.660397      None
6  2024-01-07    30.792128         NaN          NaN    2.326220     Sunny
7  2024-01-08    22.674347   63.491556          NaN    7.489773     Sunny
8  2024-01-09          NaN   65.151008          NaN    2.083668    Cloudy
9  2024-01-10    20.425600   58.511082  1070.790972         NaN     Sunny
10 2024-01-11          NaN   21.624576  1021.563358         NaN    Cloudy
11 2024-01-12    10.342702   59.469722  1030.033485         NaN     Sunny


### Method 1: Dropping Rows with Missing Values

In [207]:
# Method 1: Drop rows with ANY missing values
method1_dropna_any = weather_data.dropna()
print("Method 1a - Drop rows with ANY missing values:")
print(f"Original shape: {weather_data.shape}")
print(f"After dropping: {method1_dropna_any.shape}")
print(f"Data loss: {len(weather_data) - len(method1_dropna_any)} rows ({((len(weather_data) - len(method1_dropna_any))/len(weather_data)*100):.1f}%)")

# Method 1b: Drop rows with ALL missing values (less aggressive)
method1_dropna_all = weather_data.dropna(how='all')
print(f"\nMethod 1b - Drop rows with ALL missing values:")
print(f"After dropping: {method1_dropna_all.shape}")
print(f"Data loss: {len(weather_data) - len(method1_dropna_all)} rows")

# Method 1c: Drop rows based on specific columns
method1_dropna_subset = weather_data.dropna(subset=['temperature', 'pressure'])
print(f"\nMethod 1c - Drop rows missing temperature OR pressure:")
print(f"After dropping: {method1_dropna_subset.shape}")
print(f"Data loss: {len(weather_data) - len(method1_dropna_subset)} rows ({((len(weather_data) - len(method1_dropna_subset))/len(weather_data)*100):.1f}%)")

Method 1a - Drop rows with ANY missing values:
Original shape: (100, 6)
After dropping: (18, 6)
Data loss: 82 rows (82.0%)

Method 1b - Drop rows with ALL missing values:
After dropping: (100, 6)
Data loss: 0 rows

Method 1c - Drop rows missing temperature OR pressure:
After dropping: (47, 6)
Data loss: 53 rows (53.0%)


### Method 2: Forward Fill and Backward Fill

In [208]:
# Method 2a: Forward Fill - use last valid observation
method2_ffill = weather_data.fillna(method='ffill')

# Method 2b: Backward Fill - use next valid observation  
method2_bfill = weather_data.fillna(method='bfill')

# Method 2c: Combine forward and backward fill
method2_combined = weather_data.fillna(method='ffill').fillna(method='bfill')

print("SUMMARY STATISTICS COMPARISON - Forward/Backward Fill Methods")
print("=" * 70)

# Create comparison of summary statistics for numeric columns
for col in numeric_columns:
    print(f"\n{col.upper()}:")
    print("-" * 40)
    
    # Calculate statistics for original data (excluding NaN)
    original_stats = weather_data[col].describe()
    ffill_stats = method2_ffill[col].describe()
    bfill_stats = method2_bfill[col].describe()
    combined_stats = method2_combined[col].describe()
    
    # Create comparison DataFrame
    stats_comparison = pd.DataFrame({
        'Original': original_stats,
        'Forward_Fill': ffill_stats,
        'Backward_Fill': bfill_stats,
        'Combined': combined_stats
    })
    
    print(stats_comparison.round(3))
    
    # Show the differences from original
    print(f"\nDifference from original mean:")
    print(f"Forward Fill: {(ffill_stats['mean'] - original_stats['mean']):.3f}")
    print(f"Backward Fill: {(bfill_stats['mean'] - original_stats['mean']):.3f}")
    print(f"Combined: {(combined_stats['mean'] - original_stats['mean']):.3f}")
    
    print(f"\nDifference from original std:")
    print(f"Forward Fill: {(ffill_stats['std'] - original_stats['std']):.3f}")
    print(f"Backward Fill: {(bfill_stats['std'] - original_stats['std']):.3f}")
    print(f"Combined: {(combined_stats['std'] - original_stats['std']):.3f}")

print(f"\n" + "=" * 70)
print("KEY INSIGHTS:")
print("• Forward fill tends to create 'plateaus' where values repeat")
print("• Backward fill can create similar artifical patterns") 
print("• Combined approach eliminates missing values completely")
print("• All methods preserve the range (min/max) of original data")
print("• Standard deviation may increase due to repeated values")

SUMMARY STATISTICS COMPARISON - Forward/Backward Fill Methods

TEMPERATURE:
----------------------------------------
       Original  Forward_Fill  Backward_Fill  Combined
count    68.000       100.000        100.000   100.000
mean     13.918        15.004         14.658    15.004
std       9.038         9.127          8.706     9.127
min      -4.876        -4.876         -4.876    -4.876
25%       9.170         9.556          9.817     9.556
50%      13.210        13.210         15.870    13.210
75%      18.954        22.812         18.616    22.812
max      33.523        33.523         33.523    33.523

Difference from original mean:
Forward Fill: 1.085
Backward Fill: 0.740
Combined: 1.085

Difference from original std:
Forward Fill: 0.088
Backward Fill: -0.332
Combined: 0.088

HUMIDITY:
----------------------------------------
       Original  Forward_Fill  Backward_Fill  Combined
count    69.000       100.000        100.000   100.000
mean     58.522        58.364         57.523    

/var/folders/s4/35mz08191h37fr7zq4g0m_d40000gn/T/ipykernel_9929/1044753617.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  method2_ffill = weather_data.fillna(method='ffill')
/var/folders/s4/35mz08191h37fr7zq4g0m_d40000gn/T/ipykernel_9929/1044753617.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  method2_bfill = weather_data.fillna(method='bfill')
/var/folders/s4/35mz08191h37fr7zq4g0m_d40000gn/T/ipykernel_9929/1044753617.py:8: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  method2_combined = weather_data.fillna(method='ffill').fillna(method='bfill')


### Method 3: Statistical Imputation (Mean, Median, Mode)

In [209]:
# Method 3: Statistical Imputation
method3_mean = weather_data.copy()
method3_median = weather_data.copy()

# Fill numeric columns with mean
numeric_columns = ['temperature', 'humidity', 'pressure', 'wind_speed']
for col in numeric_columns:
    method3_mean[col] = method3_mean[col].fillna(method3_mean[col].mean())
    method3_median[col] = method3_median[col].fillna(method3_median[col].median())

# Fill categorical column with mode
mode_condition = weather_data['condition'].mode()[0]  # Get the most frequent value
method3_mean['condition'] = method3_mean['condition'].fillna(mode_condition)
method3_median['condition'] = method3_median['condition'].fillna(mode_condition)

print("SUMMARY STATISTICS COMPARISON - Statistical Imputation Methods")
print("=" * 70)

# Create comprehensive comparison of summary statistics for numeric columns
for col in numeric_columns:
    print(f"\n{col.upper()}:")
    print("-" * 40)
    
    # Calculate statistics for original data (excluding NaN)
    original_stats = weather_data[col].describe()
    mean_stats = method3_mean[col].describe()
    median_stats = method3_median[col].describe()
    
    # Create comparison DataFrame
    stats_comparison = pd.DataFrame({
        'Original': original_stats,
        'Mean_Imputed': mean_stats,
        'Median_Imputed': median_stats
    })
    
    print(stats_comparison.round(3))
    
    # Show the differences from original
    print(f"\nImputation values used:")
    print(f"Mean: {weather_data[col].mean():.3f}")
    print(f"Median: {weather_data[col].median():.3f}")
    
    print(f"\nDifference from original mean:")
    print(f"Mean Imputation: {(mean_stats['mean'] - original_stats['mean']):.3f}")
    print(f"Median Imputation: {(median_stats['mean'] - original_stats['mean']):.3f}")
    
    print(f"\nDifference from original std:")
    print(f"Mean Imputation: {(mean_stats['std'] - original_stats['std']):.3f}")
    print(f"Median Imputation: {(median_stats['std'] - original_stats['std']):.3f}")

print(f"\n" + "=" * 70)
print("CATEGORICAL VARIABLE:")
print(f"Condition mode used for imputation: {mode_condition}")
print(f"Missing values after imputation:")
print(f"Mean method: {method3_mean.isnull().sum().sum()}")
print(f"Median method: {method3_median.isnull().sum().sum()}")

print(f"\n" + "=" * 70)
print("KEY INSIGHTS:")
print("• Mean imputation preserves the original mean exactly")
print("• Median imputation may slightly shift the mean toward the median") 
print("• Both methods reduce variance (standard deviation)")
print("• Mean imputation more sensitive to outliers than median")
print("• Statistical imputation ignores temporal patterns in time series")

SUMMARY STATISTICS COMPARISON - Statistical Imputation Methods

TEMPERATURE:
----------------------------------------
       Original  Mean_Imputed  Median_Imputed
count    68.000       100.000         100.000
mean     13.918        13.918          13.692
std       9.038         7.435           7.443
min      -4.876        -4.876          -4.876
25%       9.170        11.580          11.580
50%      13.210        13.918          13.210
75%      18.954        17.081          17.081
max      33.523        33.523          33.523

Imputation values used:
Mean: 13.918
Median: 13.210

Difference from original mean:
Mean Imputation: 0.000
Median Imputation: -0.227

Difference from original std:
Mean Imputation: -1.603
Median Imputation: -1.595

HUMIDITY:
----------------------------------------
       Original  Mean_Imputed  Median_Imputed
count    69.000       100.000         100.000
mean     58.522        58.522          58.816
std      19.613        16.255          16.261
min      21.625  

### Method 4: Interpolation

In [210]:
# Method 4: Interpolation
method4_linear = weather_data.copy()
method4_polynomial = weather_data.copy()

# Linear interpolation for numeric columns
for col in numeric_columns:
    method4_linear[col] = method4_linear[col].interpolate(method='linear')
    
# Polynomial interpolation for numeric columns  
for col in numeric_columns:
    method4_polynomial[col] = method4_polynomial[col].interpolate(method='polynomial', order=2)

# For categorical data, use forward fill as interpolation doesn't work
method4_linear['condition'] = method4_linear['condition'].fillna(method='ffill')
method4_polynomial['condition'] = method4_polynomial['condition'].fillna(method='ffill')

print("SUMMARY STATISTICS COMPARISON - Interpolation Methods")
print("=" * 70)

# Create comparison of summary statistics for numeric columns
for col in numeric_columns:
    print(f"\n{col.upper()}:")
    print("-" * 40)
    
    # Calculate statistics for original data (excluding NaN)
    original_stats = weather_data[col].describe()
    linear_stats = method4_linear[col].describe()
    polynomial_stats = method4_polynomial[col].describe()
    
    # Create comparison DataFrame
    stats_comparison = pd.DataFrame({
        'Original': original_stats,
        'Linear_Interp': linear_stats,
        'Polynomial_Interp': polynomial_stats
    })
    
    print(stats_comparison.round(3))
    
    # Show the differences from original
    print(f"\nDifference from original mean:")
    print(f"Linear Interpolation: {(linear_stats['mean'] - original_stats['mean']):.3f}")
    print(f"Polynomial Interpolation: {(polynomial_stats['mean'] - original_stats['mean']):.3f}")
    
    print(f"\nDifference from original std:")
    print(f"Linear Interpolation: {(linear_stats['std'] - original_stats['std']):.3f}")
    print(f"Polynomial Interpolation: {(polynomial_stats['std'] - original_stats['std']):.3f}")

print(f"\n" + "=" * 70)
print("Missing values after interpolation:")
print(f"Linear method: {method4_linear.isnull().sum().sum()}")
print(f"Polynomial method: {method4_polynomial.isnull().sum().sum()}")

# Show the difference between interpolation methods
print(f"\n" + "=" * 70)
print("INTERPOLATION COMPARISON - Sample values (humidity, rows 18-28):")
interpolation_comparison = pd.DataFrame({
    'Original': weather_data.loc[18:28, 'humidity'],
    'Linear': method4_linear.loc[18:28, 'humidity'],
    'Polynomial': method4_polynomial.loc[18:28, 'humidity'],
    'Mean_Fill': method3_mean.loc[18:28, 'humidity']
})
print(interpolation_comparison.round(2))

print(f"\n" + "=" * 70)
print("KEY INSIGHTS:")
print("• Linear interpolation creates smooth transitions between known values")
print("• Polynomial interpolation can create more complex curves but may overshoot")
print("• Both methods preserve temporal relationships in time series data")
print("• Interpolation works best with ordered data and short gaps")
print("• May create false precision for long missing data sequences")

SUMMARY STATISTICS COMPARISON - Interpolation Methods

TEMPERATURE:
----------------------------------------
       Original  Linear_Interp  Polynomial_Interp
count    68.000        100.000            100.000
mean     13.918         14.831             16.249
std       9.038          8.400             10.928
min      -4.876         -4.876             -7.885
25%       9.170         10.272              9.666
50%      13.210         15.484             15.773
75%      18.954         20.833             21.776
max      33.523         33.523             43.002

Difference from original mean:
Linear Interpolation: 0.913
Polynomial Interpolation: 2.331

Difference from original std:
Linear Interpolation: -0.638
Polynomial Interpolation: 1.890

HUMIDITY:
----------------------------------------
       Original  Linear_Interp  Polynomial_Interp
count    69.000        100.000            100.000
mean     58.522         57.943             50.835
std      19.613         18.058             35.746
min  

/var/folders/s4/35mz08191h37fr7zq4g0m_d40000gn/T/ipykernel_9929/4293578536.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  method4_linear['condition'] = method4_linear['condition'].fillna(method='ffill')
/var/folders/s4/35mz08191h37fr7zq4g0m_d40000gn/T/ipykernel_9929/4293578536.py:15: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  method4_polynomial['condition'] = method4_polynomial['condition'].fillna(method='ffill')


### Summary of Missing Data Handling Methods

**Method 1: Dropping Data**
- **Pros**: Simple, no assumptions about missing values, preserves data integrity for remaining observations
- **Cons**: Can lead to significant data loss, may introduce bias if missingness is not random, reduces statistical power
- **Best for**: When missing data is truly random and you have plenty of data

**Method 2: Forward/Backward Fill**
- **Pros**: Preserves temporal patterns, works well for time series data, no data loss
- **Cons**: May not be realistic (carries forward outdated values), can create artificial patterns
- **Best for**: Time series data where values change gradually

**Method 3: Statistical Imputation (Mean/Median/Mode)**
- **Pros**: Simple, preserves overall distribution mean, works for any data type
- **Cons**: Reduces variance, ignores relationships between variables, may not reflect true patterns
- **Best for**: Large datasets where individual missing values won't significantly impact analysis

**Method 4: Interpolation**
- **Pros**: Creates realistic values based on trend, preserves patterns, smooth transitions
- **Cons**: May create false precision, assumes smooth relationships, computationally more complex
- **Best for**: Time series or ordered data with clear trends

**Key Considerations:**
1. **Amount of missing data**: High missingness may require dropping variables/observations
2. **Pattern of missingness**: Random vs systematic missing data requires different approaches
3. **Type of analysis**: Some methods better preserve statistical properties needed for specific analyses
4. **Domain knowledge**: Understanding why data is missing helps choose appropriate method